estateagent/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from .forms import EstateagentAuthForm


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^documents/', include('documents.urls')),
    url(r'^', include('home.urls', namespace="home")),
    url(r'^articles/', include('articles.urls', namespace="articles")),
    url(r'^people/', include('people.urls', namespace="people")),
    url(r'^places/', include('places.urls', namespace="places")),
    url(r'^rent/', include('rent.urls', namespace="rent")),
    url(r'^sale/', include('sale.urls', namespace="sale")),
    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^accounts/login/?$', views.login, name='login',
        kwargs={
            'template_name': 'registration/login.html',
            'authentication_form': EstateagentAuthForm
        }
       ),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import url

from .views import Home

app_name = 'home'

urlpatterns = [
    url(r'^$', Home.as_view(), name='index'),
]

people/urls.py
from django.conf.urls import url

from . import views
from .views import Register

app_name = 'people'

urlpatterns = [
    url(r'^agent/(?P<user_id>[0-9]+)/$', views.agent_detail, name='agent_detail'),
    url(r'^owner/(?P<user_id>[0-9]+)/$', views.owner_detail, name='owner_detail'),
    url(r'^my_profile/$', views.my_profile, name='my_profile'),
    url(r'^my_preferences/$', views.my_preferences, name='my_preferences'),
    url(r'^tenant/(?P<user_id>[0-9]+)/$', views.tenant_detail, name='tenant_detail'),
    url(r'^owner/property_list/(?P<user_id>[0-9]+)/$', views.owner_property_list, name='owner_property_list'),
    url(r'^tenant/property_list/(?P<user_id>[0-9]+)/$', views.tenant_property_list, name='tenant_property_list'),
    url(r'^register/$', Register.as_view(), name='register'),
]

home/views.py
from django.core.urlresolvers import reverse
from django.views import View
from django.shortcuts import render
from django.contrib.messages import get_messages
from places.models import Property
from search.forms import SimpleSearchForm
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)

class Home(View):
    """Home page class-based view

    Args:
        View (:obj:Django View base class, required)

    """

    def common_context(self):
        """Common data for the context var: both get() and post() will
        require these
        """

        # latest_properties: last four updated rent or sale properties
        context = {
            'latest_properties': Property.objects.order_by('-updated')[:4],
            'page_title': 'Estate Agent',
            'reverse': reverse("home:index"),
        }
        return context

    def get(self, request):
        """get http method: search form will be empty
        """
        context = self.common_context()
        context.update({
            'form': SimpleSearchForm(),
            'messages': get_messages(request),
        })
        return render(request, 'home/index.html', context)

    def post(self, request):
        """post http method: search form will be submitted
        """
        form = SimpleSearchForm(request.POST)

        context = self.common_context()
        context.update({
            'template': 'home/index.html',
        })
        # Process the form and return the results
        return form.process_post(request, context)

home/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        {% block meta %}{% endblock %}
        <!-- Bootstrap Core CSS -->
        {% bootstrap_css %}
        <link href="{% static "tools/css/global.css" %}" rel="stylesheet">

        <!-- Custom CSS -->
        {% block custom_css %}{% endblock %}
        <!-- Custom CSS Finished -->

        <link href="{% static "tools/jquery-ui-1.12.1/jquery-ui.css" %}" rel="stylesheet">
    </head>
    <body>
        <div class="all-content">
            <!-- Navigation -->
            <nav class="navbar navbar-static-top global-navigation" >
                <div class="container global-navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-nav global-navbar" href="{% url 'home:index' %}">Estate Agency</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'sale:index' %}">Buy</a></li>
                            <li><a href="{% url 'rent:index' %}">Rent</a></li>
                            <li><a href="/pages/sell/">Sell</a></li>
                            <li><a href="/pages/about/">About</a></li>
                            <li><a href="/pages/contact/">Contact</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}">Log out</a></li>
                            <li><a href="{% url 'people:my_profile' %}"><small><em>{{ user.username }}</em></small></a></li>
                            {% else %}
                            <li><a href="{% url 'login' %}?next={{ request.get_full_path|urlencode }}">Log in</a></li>
                            <li><a href="{% url 'people:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

            <!-- Page Content -->
            <div class="page-content">
                <div class="container">
                    <div class="bg"></div>
                </div>

                {% block content %}{% endblock %}
            </div>
            <!-- Page Content Ends-->

            <footer>
                <div class="footer global-footer">
                    <div class="container">
                        <p>&copy; 2017 Standard Candle Software LTD. All rights reserved. Contact: davefelce@gmail.com</p>
                    </div>
                </div>
            </footer>
        </div>

        <!-- jQuery -->
        <script src="{% static "tools/JQuery-3.1.1-dist/jquery-3.1.1.js" %}"></script>
        <!-- Bootstrap Core JavaScript -->
        {% bootstrap_javascript %}
        <script src="{% static "tools/jquery-ui-1.12.1/jquery-ui.js" %}" type="text/javascript" ></script>

        <!-- Custom Scripts -->
        {% block custom_scripts %}{% endblock %}
        <script src="{% static "tools/js/global.js" %}" type="text/javascript" ></script>
        <!-- Custom Scripts Finished -->

    </body>
</html>