estateagent/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from .forms import EstateagentAuthForm


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^documents/', include('documents.urls')),
    url(r'^', include('home.urls', namespace="home")),
    url(r'^articles/', include('articles.urls', namespace="articles")),
    url(r'^people/', include('people.urls', namespace="people")),
    url(r'^places/', include('places.urls', namespace="places")),
    url(r'^rent/', include('rent.urls', namespace="rent")),
    url(r'^sale/', include('sale.urls', namespace="sale")),
    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^accounts/login/?$', views.login, name='login',
        kwargs={
            'template_name': 'registration/login.html',
            'authentication_form': EstateagentAuthForm
        }
       ),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import url

from .views import Home

app_name = 'home'

urlpatterns = [
    url(r'^$', Home.as_view(), name='index'),
]

people/urls.py
from django.conf.urls import url

from . import views
from .views import Register

app_name = 'people'

urlpatterns = [
    url(r'^agent/(?P<user_id>[0-9]+)/$', views.agent_detail, name='agent_detail'),
    url(r'^owner/(?P<user_id>[0-9]+)/$', views.owner_detail, name='owner_detail'),
    url(r'^my_profile/$', views.my_profile, name='my_profile'),
    url(r'^my_preferences/$', views.my_preferences, name='my_preferences'),
    url(r'^tenant/(?P<user_id>[0-9]+)/$', views.tenant_detail, name='tenant_detail'),
    url(r'^owner/property_list/(?P<user_id>[0-9]+)/$', views.owner_property_list, name='owner_property_list'),
    url(r'^tenant/property_list/(?P<user_id>[0-9]+)/$', views.tenant_property_list, name='tenant_property_list'),
    url(r'^register/$', Register.as_view(), name='register'),
]

places/urls.py
from django.conf.urls import url

from . import views

app_name = 'places'

urlpatterns = [
    url(
        r'^for_rental/detail/(?P<property_id>[0-9]+)/$',
        views.RentalDetail.as_view(),
        name='rental_detail'
    ),
    url(
        r'^for_sale/detail/(?P<property_id>[0-9]+)/$',
        views.SaleDetail.as_view(),
        name='sale_detail'
    ),
    url(
        r'^owned/detail/(?P<property_id>[0-9]+)/$',
        views.owned_detail,
        name='owned_detail'
    ),
    url(
        r'^rented/detail/(?P<property_id>[0-9]+)/$',
        views.rented_detail,
        name='rented_detail'
    ),
]

people/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    address = models.TextField(max_length=300)
    town_or_city = models.CharField(max_length=100)
    county = models.CharField(max_length=100)
    postcode = models.CharField(max_length=10)
    number = models.CharField(max_length=30)
    email = models.EmailField()
    email_alerts = models.BooleanField(default=False)
    user_type = models.CharField(max_length=100,
                                 choices=[('public', 'Public'),
                                          ('agent', 'Agent'),
                                          ('tenant', 'Tenant'),
                                          ('owner', 'Owner')]
                                )

    rooms = models.IntegerField(default=0)
    floors = models.IntegerField(default=0)
    bathrooms = models.IntegerField(default=0)
    bedrooms = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    class Meta:
        managed = True
        db_table = 'details'
        verbose_name_plural = "details"

places/models.py
from django.db import models


from people.models import Details

class Property(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Details, on_delete=models.DO_NOTHING)
    for_rent = models.BooleanField() # TODO: Change this to an enum describing the type
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    postcode = models.CharField(max_length=10)
    description = models.TextField(max_length=5000)
    price = models.IntegerField()
    rooms = models.IntegerField()
    floors = models.IntegerField()
    bathrooms = models.IntegerField()
    bedrooms = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'property'
        verbose_name_plural = "properties"

people/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    address = forms.CharField(max_length=300,
                              widget=forms.Textarea(
                                  attrs={'width': '100%', 'class': 'form-control'}
                              ))
    town_or_city = forms.CharField(max_length=100,
                                   widget=forms.TextInput(
                                       attrs={'width': '100%', 'class': 'form-control'}
                                   ))
    county = forms.CharField(max_length=100,
                             widget=forms.TextInput(
                                 attrs={'width': '100%', 'class': 'form-control'}
                             ))
    postcode = forms.CharField(max_length=10,
                               widget=forms.TextInput(
                                   attrs={'width': '100%', 'class': 'form-control'}
                               ))
    number = forms.CharField(max_length=30,
                             help_text="Your contact telephone or mobile number",
                             widget=forms.TextInput(
                                 attrs={'width': '50%', 'class': 'form-control'}
                             ))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'width': '100%', 'class': 'form-control'}))
    rooms = forms.IntegerField(min_value=0,
                                        widget=forms.NumberInput(attrs={'width': '25%', 'class': 'form-control'}))
    floors = forms.IntegerField(min_value=0,
                                         widget=forms.NumberInput(attrs={'width': '25%', 'class': 'form-control'}))
    bathrooms = forms.IntegerField(min_value=0,
                                            widget=forms.NumberInput(attrs={'width': '25%', 'class': 'form-control'}))
    bedrooms = forms.IntegerField(min_value=0,
                                           widget=forms.NumberInput(attrs={'width': '25%', 'class': 'form-control'}))
    email_alerts = forms.BooleanField(
        help_text="Select to receive regular email updates on properties matching your searches",
        required=False
    )
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))

    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'password1', 'password2', 'username')
        widgets = {
            'first_name': forms.TextInput(attrs={'width': '100%', 'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'width': '100%', 'class': 'form-control'}),
            'username': forms.TextInput(attrs={'width': '100%', 'class': 'form-control'}),
        }

people/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.views import View
from django.contrib.staticfiles.templatetags.staticfiles import static

# from django.contrib.auth.models import User
from .models import Details
from .forms import RegisterForm

# TODO: Remember a lot of these templates were copies of the original detail.html and login.html
# login.html was usually a list of objects to display to became property_list.html, where detail.html got
# copied into the three people template dirs.  They need sorting out, and were left mostly as they
# were to get the tests working

# Display details of a single agent, so person obj here will be of type 'agent'
def agent_detail(request, user_id):
    """Detail page for a single agent (Person obj)

    Args:
        user_id: id to retrieve Person obj
    """
    person = get_object_or_404(Details, pk=user_id)
    return render(request, 'people/agent/detail.html', {'person': person, 'page_title': 'Agent detail'})

# Display details of a single owner, so person obj here will be of type 'owner'
@login_required
def owner_detail(request, user_id):
    """Detail page for a single property owner (Person obj)

    Args:
        user_id: id to retrieve Person obj
    """
    person = get_object_or_404(Details, pk=user_id)
    return render(request, 'people/owner/detail.html', {'person': person, 'page_title': 'Owner detail'})

@login_required
def my_profile(request):
    """ Profile page for the current user - linked to from right navbar name link """

    user_id = request.user.details.id  # id of people.Details rather than Django user
    person = get_object_or_404(Details, pk=user_id)
    return render(request, 'people/my_profile/index.html', {'person': person, 'page_title': 'My profile'})

@login_required
def my_preferences(request):
    """ Preferences page for the current user - linked to from profile page """

    user_id = request.user.details.id  # id of people.Details rather than Django user
    person = get_object_or_404(Details, pk=user_id)
    return render(request, 'people/my_profile/preferences.html', {'person': person, 'page_title': 'My preferences'})

# Display details of a single tenant, so person obj here will be of type 'tenant'
def tenant_detail(request, user_id):
    """Detail page for a single tenant (Person obj)

    Args:
        user_id: id to retrieve Person obj
    """
    person = get_object_or_404(Details, pk=user_id)
    return render(request, 'people/tenant/detail.html', {'person': person, 'page_title': 'Tenant detail'})

def owner_property_list(request, user_id):
    """List of properties belonging to owner (Person obj)

    Args:
        user_id: id to retrieve Person obj

    TODO:
        Maybe this will be 'display properties owned
        by me' or something, in which case user_id would be redundant and the user_id of the
        logged in user used. The details.html already lists property owned/rented by the person

    """
    person = get_object_or_404(Details, pk=user_id)
    return render(request, 'people/owner/property_list.html', {'person': person, 'page_title': 'Owner properties'})

def tenant_property_list(request, user_id):
    """Listing page for properties (having been) rented by tenant (Person obj)

    Args:
        user_id: id to retrieve Person obj

    TODO:
        Clearly delineated 'current' property at top, then historic list?
        This probably needs a separate method for 'display my rented properties'

    """
    person = get_object_or_404(Details, pk=user_id)
    return render(request, 'people/tenant/property_list.html', {'person': person, 'page_title': 'Tenant properties'})

class Register(View):
    def get(self, request):
        """get http method: search form will be empty
        """
        form = RegisterForm()
        return render(request, 'people/register.html', {'form': form})

    def post(self, request):
        """post http method: registration form will be submitted
        """

        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.details.address = form.cleaned_data.get('address')
            user.details.town_or_city = form.cleaned_data.get('town_or_city')
            user.details.county = form.cleaned_data.get('county')
            user.details.postcode = form.cleaned_data.get('postcode')
            user.details.number = form.cleaned_data.get('number')
            user.details.email = form.cleaned_data.get('email')
            user.details.rooms = form.cleaned_data.get('rooms')
            user.details.floors = form.cleaned_data.get('floors')
            user.details.bathrooms = form.cleaned_data.get('bathrooms')
            user.details.bedrooms = form.cleaned_data.get('bedrooms')
            user.details.email_alerts = form.cleaned_data.get('email_alerts')
            # All users registering via the site are 'public' but can be manually
            # changed later via the admin interface, e.g. into a 'tenant'
            user.details.user_type = 'public'
            user.details.image_original = 'people/original/anonymous_user.png'
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home:index')
        else:
            return render(request, 'people/register.html', {'form': form})

people/templates/people/owner/detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block meta %}
<title>Owner detail</title>
{% endblock %}

{% block custom_css %}
<link href="{% static "people/css/people.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container index-page">
    <div class="row">
        <!-- <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
            <a href="edit.html" >Edit Profile</a>
            <a href="edit.html" >Logout</a>
            <p class=" text-info">May 05,2014,03:00 pm </p>
        </div> -->
        <div class="panel ">
            <div class="panel-body">
                <div class="row person-contact">
                    <div class=" col-sm-9 ">
                        <div class="row">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Name:</td>
                                        <td>{{ person.user.username }}</td>
                                    </tr>
                                    <tr>
                                        <td>Address</td>
                                        <td>{{ person.address }}</td>
                                    </tr>
                                    <tr>
                                        <td>Town or City</td>
                                        <td>{{ person.town_or_city }}</td>
                                    </tr>
                                    <tr>
                                        <td>County</td>
                                        <td>{{ person.county }}</td>
                                    </tr>
                                    <tr>
                                        <td>Postcode</td>
                                        <td>{{ person.postcode }}</td>
                                    </tr>
                                    <tr>
                                        <tr>
                                            <td>Email</td>
                                            <td><a href="mailto:{{ person.email }}">{{ person.email }}</a></td>
                                        </tr>
                                        <td>Phone Number</td>
                                        <td>{{ person.number }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <a href="#" class="btn btn-person">Properties Rented</a>
                        <a href="{% url 'people:owner_property_list' person.id %}" class="btn btn-person">Properties Owned</a>
                        <a href="#" class="btn btn-person">Properties Sold</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

people/templates/people/owner/property_list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block meta %}
<title>Owner properties</title>
{% endblock %}

{% block custom_css %}
<link href="{% static "people/css/property_list.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container index-page">
    {% for property in person.property_set.all %}
    <div class="row property-bottom">
        <div class="col-sm-5 col-xs-12" >
            <a href="{% url 'places:owned_detail' property.id %}" >
                <img src="{{ property.image_standard.url }}" class="img-thumbnail img-responsive pull-left ">
            </a>
        </div>
        <div class="col-sm-7 plist-text col-xs-12" >
            <div class="row">
                <h2 class="global-header plist-header">{{ property.short_description }}</h2>
                <div class="row property-bottom-2 ">
                    <p>{{ property.description|safe }}</p>
                    <div class="col-sm-6 property-list">
                        <ul class="list-group">
                            <li class="list-group-item justify-content-between">
                                Rooms:
                                <span class="badge badge-default badge-pill">{{property.rooms}}</span>
                            </li>
                            <li class="list-group-item justify-content-between">
                                Bedrooms:
                                <span class="badge badge-default badge-pill">{{property.bedrooms}}</span>
                            </li>
                            <li class="list-group-item justify-content-between">
                                Bathrooms:
                                <span class="badge badge-default badge-pill">{{property.bathrooms}}</span>
                            </li>
                            <li class="list-group-item justify-content-between">
                                Floors:
                                <span class="badge badge-default badge-pill">{{property.floors}}</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <h5>{{ property.town_or_city }}</h5>
                    <h5 class="plist-desc">{{ property.postcode }}</h5>
                    <div class="plist-bottom">
                        {%  if property.for_rent %}
                        <h4>Price: £{{ property.price }} pcm</h4>
                        {% else %}
                        <h4>Price: £{{ property.price }}</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}